"""Database access layer for the PennyMe backend.

All functions raise on failure — there are no silent returns on error.
Callers must handle exceptions explicitly.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional

import geopandas as gpd
import psycopg2
import psycopg2.extras
from loguru import logger
from sqlalchemy import create_engine

# login.json lives in the backend/ directory (one level up from this package)
_LOGIN_PATH = Path(__file__).resolve().parent.parent / "db_login.json"
assert _LOGIN_PATH.exists(), f"Missing database login file: {_LOGIN_PATH}"

# Whitelist of column names that callers may update via update_machine_fields.
# Never derive this set from user input.
_ALLOWED_MACHINE_FIELDS = frozenset(
    {
        "name",
        "area",
        "address",
        "latitude",
        "longitude",
        "machine_status",
        "multimachine",
        "num_coins",
        "paywall",
        "external_url",
        "internal_url",
        "last_updated",
    }
)


# ---------------------------------------------------------------------------
# Schema creation
# ---------------------------------------------------------------------------

_CREATE_TABLES_SQL = """
CREATE TABLE IF NOT EXISTS machines (
    id             INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name           TEXT    NOT NULL,
    area           TEXT    NOT NULL,
    address        TEXT    NOT NULL,
    geom           geometry(Point, 4326) NOT NULL,
    machine_status TEXT    NOT NULL DEFAULT 'available',
    status TEXT    NOT NULL DEFAULT 'unvisited',
    multimachine   INTEGER NOT NULL DEFAULT 1,
    num_coins      INTEGER NOT NULL DEFAULT 4,
    paywall        BOOLEAN NOT NULL DEFAULT FALSE,
    external_url   TEXT,
    internal_url   TEXT,
    last_updated   DATE    NOT NULL
);

CREATE TABLE IF NOT EXISTS pending_changes (
    id             INTEGER   PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    machine_id     INTEGER   REFERENCES machines(id),
    change_type    TEXT      NOT NULL DEFAULT 'update',
    name           TEXT      NOT NULL,
    area           TEXT      NOT NULL,
    address        TEXT      NOT NULL,
    latitude       REAL      NOT NULL,
    longitude      REAL      NOT NULL,
    machine_status TEXT      NOT NULL DEFAULT 'available',
    multimachine   INTEGER   NOT NULL DEFAULT 1,
    num_coins      INTEGER   NOT NULL DEFAULT 4,
    paywall        BOOLEAN   NOT NULL DEFAULT FALSE,
    external_url   TEXT,
    internal_url   TEXT,
    last_updated   DATE      NOT NULL,
    submitted_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at    TIMESTAMP,
    submitted_by   TEXT,
    change_summary TEXT      NOT NULL,
    status         TEXT      NOT NULL DEFAULT 'open',
    image_path     TEXT
);

CREATE INDEX IF NOT EXISTS machines_geom_gist ON machines USING GIST (geom);
"""


def create_tables() -> None:
    """Create the machines and pending_changes tables if they do not exist.

    Safe to call on an already-initialised database — all statements use
    ``CREATE TABLE IF NOT EXISTS``.

    Raises:
        psycopg2.Error: On any database error.
    """
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(_CREATE_TABLES_SQL)
        conn.commit()
    logger.info("Tables created (or already exist).")


# ---------------------------------------------------------------------------
# Connection
# ---------------------------------------------------------------------------


def get_connection() -> psycopg2.extensions.connection:
    """Return a new psycopg2 connection using credentials from login.json.

    Raises:
        FileNotFoundError: If login.json does not exist.
        psycopg2.OperationalError: If the database connection fails.
    """
    with open(_LOGIN_PATH, "r") as f:
        login = json.load(f)
    return psycopg2.connect(**login)


_engine = None


def get_engine():
    """Return a cached SQLAlchemy engine used by geopandas operations."""
    global _engine
    if _engine is None:
        with open(_LOGIN_PATH) as f:
            login = json.load(f)
        url = "postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}".format(
            **login
        )
        _engine = create_engine(url)
    return _engine


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _row_to_geojson_feature(row: dict) -> dict:
    """Convert a machines-table row dict to a GeoJSON Feature dict."""
    props: Dict[str, Any] = {
        "name": row["name"],
        "area": row["area"],
        "address": row["address"],
        "external_url": row["external_url"] or "null",
        "internal_url": row["internal_url"] or "null",
        "machine_status": row["machine_status"],
        "id": row["id"],
        "last_updated": str(row["last_updated"]),
    }
    if row.get("multimachine", 1) != 1:
        props["multimachine"] = row["multimachine"]
    if row.get("num_coins", 4) != 4:
        props["num_coins"] = row["num_coins"]
    if row.get("paywall", False):
        props["paywall"] = row["paywall"]
    return {
        "type": "Feature",
        "geometry": {
            "type": "Point",
            "coordinates": [row["longitude"], row["latitude"]],
        },
        "properties": props,
    }


def _normalise_url(value: Optional[str]) -> Optional[str]:
    """Return None for missing/null URL strings, otherwise the raw value."""
    return None if value in (None, "null") else value


# ---------------------------------------------------------------------------
# Read operations
# ---------------------------------------------------------------------------


def get_machine_as_geojson(machine_id: int) -> dict:
    """Return a single machine as a GeoJSON Feature.

    Raises:
        KeyError: If no machine with that ID exists.
        psycopg2.Error: On any database error.
    """
    with get_connection() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(
                "SELECT *, ST_X(geom) AS longitude, ST_Y(geom) AS latitude"
                " FROM machines WHERE id = %s",
                (machine_id,),
            )
            row = cur.fetchone()
    if row is None:
        raise KeyError(f"Machine {machine_id} not found in database")
    return _row_to_geojson_feature(dict(row))


def get_all_machines_geojson() -> dict:
    """Return all machines as a GeoJSON FeatureCollection.

    Raises:
        psycopg2.Error: On any database error.
    """
    gdf = gpd.read_postgis(
        "SELECT * FROM machines ORDER BY id",
        get_engine(),
        geom_col="geom",
    )
    return json.loads(gdf.to_json())


def has_open_pending_change(machine_id: int) -> bool:
    """Return True if there is an open (unreviewed) pending change for this machine.

    Raises:
        psycopg2.Error: On any database error.
    """
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT 1 FROM pending_changes"
                " WHERE machine_id = %s AND status = 'open' LIMIT 1",
                (machine_id,),
            )
            return cur.fetchone() is not None


def get_nearby_machines_db(
    lat: float, lon: float, area: str, radius_m: int = 150
) -> List[Dict]:
    """Return approved machines within *radius_m* metres of the given point.

    Uses a PostGIS ``ST_DWithin`` query on a GIST-indexed geography column for
    efficient indexed radius lookup, with exact geodesic distances via
    ``ST_Distance``.

    Raises:
        psycopg2.Error: On any database error.
    """
    with get_connection() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(
                """
                SELECT id, name, address, area, machine_status,
                       ST_Distance(geom::geography,
                                   ST_MakePoint(%(lon)s, %(lat)s)::geography) AS distance_m
                FROM machines
                WHERE area = %(area)s
                  AND ST_DWithin(geom::geography,
                                 ST_MakePoint(%(lon)s, %(lat)s)::geography,
                                 %(radius_m)s)
                ORDER BY distance_m
                """,
                {"lat": lat, "lon": lon, "area": area, "radius_m": radius_m},
            )
            rows = cur.fetchall()
    return [
        {
            "id": row["id"],
            "name": row["name"],
            "address": row["address"],
            "area": row["area"],
            "machine_status": row["machine_status"],
            "distance_m": round(row["distance_m"]),
        }
        for row in rows
    ]


# ---------------------------------------------------------------------------
# Write operations – machines
# ---------------------------------------------------------------------------


def update_machine_fields(machine_id: int, fields: dict) -> None:
    """Update a subset of columns on a machine row.

    Args:
        machine_id: ID of the machine to update.
        fields: Mapping of column name → new value. All keys must appear in
            the allowed-fields whitelist to prevent SQL injection.

    Raises:
        ValueError: If *fields* is empty or contains unknown column names.
        KeyError: If no machine with *machine_id* exists.
        psycopg2.Error: On any database error.
    """
    if not fields:
        raise ValueError("No fields to update")
    unknown = set(fields) - _ALLOWED_MACHINE_FIELDS
    if unknown:
        raise ValueError(f"Unknown machine column(s): {unknown}")

    has_lat = "latitude" in fields
    has_lon = "longitude" in fields
    if has_lat != has_lon:
        raise ValueError("latitude and longitude must be supplied together")

    params = dict(fields)
    params["_machine_id"] = machine_id

    set_parts = []
    if has_lat:
        set_parts.append("geom = ST_MakePoint(%(longitude)s, %(latitude)s)")
    set_parts += [
        f'"{ k}" = %({k})s' for k in fields if k not in ("latitude", "longitude")
    ]

    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(
                f"UPDATE machines SET {', '.join(set_parts)} WHERE id = %(_machine_id)s",
                params,
            )
            if cur.rowcount == 0:
                raise KeyError(f"Machine {machine_id} not found in database")
        conn.commit()


def update_machine_from_geojson(feature: dict) -> None:
    """Apply all mutable fields from a GeoJSON Feature to the machines table.

    Raises:
        KeyError: If the machine is not found.
        psycopg2.Error: On any database error.
    """
    props = feature["properties"]
    lng, lat = feature["geometry"]["coordinates"]
    machine_id = props["id"]
    fields = {
        "name": props["name"],
        "area": props["area"],
        "address": props["address"],
        "latitude": lat,
        "longitude": lng,
        "machine_status": props.get("machine_status", "available"),
        "multimachine": props.get("multimachine", 1),
        "num_coins": props.get("num_coins", 4),
        "paywall": props.get("paywall", False),
        "external_url": _normalise_url(props.get("external_url")),
        "internal_url": _normalise_url(props.get("internal_url")),
        "last_updated": props.get("last_updated"),
    }
    update_machine_fields(machine_id, fields)


# ---------------------------------------------------------------------------
# Write operations – pending_changes
# ---------------------------------------------------------------------------


def insert_pending_change_full(
    machine_id: Optional[int],
    change_type: str,
    machine_fields: dict,
    submitted_by: Optional[str],
    change_summary: str,
) -> int:
    """Write a proposed change (create or update) to pending_changes.

    The row holds the full proposed machine state so the approver can apply
    it directly without re-reading the request.

    Args:
        machine_id: Existing machine ID for updates, None for new machines.
        change_type: ``'create'`` or ``'update'``.
        machine_fields: All mutable machine columns keyed by column name.
        submitted_by: Anonymous installation identifier of the submitter.
        change_summary: Human-readable description (``'new machine'`` or the
            ``msg`` string from ``change_machine``).

    Returns:
        The auto-assigned ``id`` of the new pending_changes row.

    Raises:
        psycopg2.Error: On any database error.
    """
    ext_url = _normalise_url(machine_fields.get("external_url"))
    int_url = _normalise_url(machine_fields.get("internal_url"))
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO pending_changes (
                    machine_id, change_type,
                    name, area, address, latitude, longitude,
                    machine_status, multimachine, num_coins, paywall,
                    external_url, internal_url, last_updated,
                    submitted_by, change_summary
                ) VALUES (
                    %(machine_id)s, %(change_type)s,
                    %(name)s, %(area)s, %(address)s, %(latitude)s, %(longitude)s,
                    %(machine_status)s, %(multimachine)s, %(num_coins)s, %(paywall)s,
                    %(external_url)s, %(internal_url)s, %(last_updated)s,
                    %(submitted_by)s, %(change_summary)s
                ) RETURNING id
                """,
                {
                    "machine_id": machine_id,
                    "change_type": change_type,
                    "name": machine_fields["name"],
                    "area": machine_fields["area"],
                    "address": machine_fields["address"],
                    "latitude": machine_fields["latitude"],
                    "longitude": machine_fields["longitude"],
                    "machine_status": machine_fields.get("machine_status", "available"),
                    "multimachine": machine_fields.get("multimachine", 1),
                    "num_coins": machine_fields.get("num_coins", 4),
                    "paywall": machine_fields.get("paywall", False),
                    "external_url": ext_url,
                    "internal_url": int_url,
                    "last_updated": machine_fields.get("last_updated"),
                    "submitted_by": submitted_by or None,
                    "change_summary": change_summary,
                },
            )
            change_id = cur.fetchone()[0]
        conn.commit()
    return change_id


def get_open_pending_changes() -> List[Dict]:
    """Return all open (unreviewed) pending changes ordered by submission time.

    Raises:
        psycopg2.Error: On any database error.
    """
    with get_connection() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(
                "SELECT * FROM pending_changes WHERE status = 'open' ORDER BY submitted_at"
            )
            rows = cur.fetchall()
    return [dict(r) for r in rows]


def approve_pending_change(change_id: int) -> int:
    """Apply a pending change to the machines table and mark it approved.

    For ``create`` changes the machine row is inserted and its new ID returned.
    For ``update`` changes the existing row is updated and the existing ID
    is returned.

    Raises:
        KeyError: If the pending change or the target machine is not found.
        ValueError: If an update change has no machine_id.
        psycopg2.Error: On any database error.
    """
    with get_connection() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute("SELECT * FROM pending_changes WHERE id = %s", (change_id,))
            row = cur.fetchone()
        if row is None:
            raise KeyError(f"Pending change {change_id} not found")
        change = dict(row)

        with conn.cursor() as cur:
            if change["change_type"] == "create":
                cur.execute(
                    """
                    INSERT INTO machines (
                        name, area, address, geom,
                        machine_status, multimachine, num_coins, paywall,
                        external_url, internal_url, last_updated
                    ) VALUES (
                        %(name)s, %(area)s, %(address)s,
                        ST_MakePoint(%(longitude)s, %(latitude)s),
                        %(machine_status)s, %(multimachine)s, %(num_coins)s, %(paywall)s,
                        %(external_url)s, %(internal_url)s, %(last_updated)s
                    ) RETURNING id
                    """,
                    change,
                )
                machine_id = cur.fetchone()[0]
            else:
                machine_id = change["machine_id"]
                if machine_id is None:
                    raise ValueError(
                        f"Update pending change {change_id} has no machine_id"
                    )
                cur.execute(
                    """
                    UPDATE machines SET
                        name           = %(name)s,
                        area           = %(area)s,
                        address        = %(address)s,
                        geom           = ST_MakePoint(%(longitude)s, %(latitude)s),
                        machine_status = %(machine_status)s,
                        multimachine   = %(multimachine)s,
                        num_coins      = %(num_coins)s,
                        paywall        = %(paywall)s,
                        external_url   = %(external_url)s,
                        internal_url   = %(internal_url)s,
                        last_updated   = %(last_updated)s
                    WHERE id = %(machine_id)s
                    """,
                    {**change, "machine_id": machine_id},
                )
                if cur.rowcount == 0:
                    raise KeyError(f"Machine {machine_id} not found for update")

            cur.execute(
                "UPDATE pending_changes"
                " SET status = 'approved', reviewed_at = NOW()"
                " WHERE id = %s",
                (change_id,),
            )
        conn.commit()
    return machine_id


def reject_pending_change(change_id: int) -> None:
    """Mark a pending change as rejected without touching the machines table.

    Raises:
        KeyError: If the pending change is not found.
        psycopg2.Error: On any database error.
    """
    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "UPDATE pending_changes"
                " SET status = 'rejected', reviewed_at = NOW()"
                " WHERE id = %s",
                (change_id,),
            )
            if cur.rowcount == 0:
                raise KeyError(f"Pending change {change_id} not found")
        conn.commit()


# ---------------------------------------------------------------------------
# Bulk file operations (used by location_differ and run_location_differ)
# ---------------------------------------------------------------------------


def dump_machines_to_file(path: str) -> None:
    """Write all machines as a GeoJSON FeatureCollection to *path*.

    Raises:
        psycopg2.Error: On any database error.
        OSError: On any file I/O error.
    """
    data = get_all_machines_geojson()
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=4)
    logger.info(f"Dumped {len(data['features'])} machines to {path}")


def upsert_machines_from_file(path: str) -> None:
    """Upsert every machine in a GeoJSON FeatureCollection file into the DB.

    Existing rows (matched by id) are fully overwritten; new rows are inserted
    with approved=TRUE.  Only the location_differ output should call this.

    Raises:
        ValueError: If the file contains no features.
        psycopg2.Error: On any database error.
        OSError: On any file I/O error.
    """
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    features = data.get("features", [])
    if not features:
        raise ValueError(f"No features found in {path}")

    with get_connection() as conn:
        with conn.cursor() as cur:
            for feature in features:
                props = feature["properties"]
                lng, lat = feature["geometry"]["coordinates"]
                cur.execute(
                    """
                    INSERT INTO machines (
                        id, name, area, address, geom,
                        machine_status, multimachine, num_coins, paywall,
                        external_url, internal_url, last_updated
                    ) VALUES (
                        %(id)s, %(name)s, %(area)s, %(address)s,
                        ST_MakePoint(%(lng)s, %(lat)s),
                        %(machine_status)s, %(multimachine)s, %(num_coins)s, %(paywall)s,
                        %(external_url)s, %(internal_url)s, %(last_updated)s
                    )
                    ON CONFLICT (id) DO UPDATE SET
                        name           = EXCLUDED.name,
                        area           = EXCLUDED.area,
                        address        = EXCLUDED.address,
                        geom           = EXCLUDED.geom,
                        machine_status = EXCLUDED.machine_status,
                        multimachine   = EXCLUDED.multimachine,
                        num_coins      = EXCLUDED.num_coins,
                        paywall        = EXCLUDED.paywall,
                        external_url   = EXCLUDED.external_url,
                        internal_url   = EXCLUDED.internal_url,
                        last_updated   = EXCLUDED.last_updated
                    """,
                    {
                        "id": props["id"],
                        "name": props["name"],
                        "area": props["area"],
                        "address": props["address"],
                        "lat": lat,
                        "lng": lng,
                        "machine_status": props.get("machine_status", "available"),
                        "multimachine": props.get("multimachine", 1),
                        "num_coins": props.get("num_coins", 4),
                        "paywall": props.get("paywall", False),
                        "external_url": _normalise_url(props.get("external_url")),
                        "internal_url": _normalise_url(props.get("internal_url")),
                        "last_updated": props.get("last_updated"),
                    },
                )
        conn.commit()
    logger.info(f"Upserted {len(features)} machines from {path}")
