def parse_location_name(x: str) -> str:
    return x.lower().replace(". ", "_").replace(" ", "_")


def remove_html_and(x):
    return x.replace("&amp;", "&")


# Mapping the areas to the country codes as in pennycollector.com
# http://209.221.138.252/AreaList.aspx
COUNTRY_TO_CODE = {
    " Private Rollers": 123,
    "Alabama": 41,
    "Alaska": 42,
    "Arizona": 43,
    "Arkansas": 44,
    "Australia": 18,
    "Austria": 19,
    "Bahamas": 117,
    "Belarus": 153,
    "Belgium": 20,
    "Bermuda": 21,
    "Brazil": 142,
    "Bulgaria": 126,
    "California": 45,
    "Canada": 22,
    "Cayman Islands": 23,
    "China": 103,
    "Colorado": 46,
    "Connecticut": 47,
    "Croatia": 108,
    "Cyprus": 115,
    "Czech Republic": 24,
    "Delaware": 48,
    "Denmark": 139,
    "Ecuador": 105,
    "England": 92,
    "Estonia": 129,
    "Finland": 98,
    "Florida": 14,
    "France": 16,
    "Georgia": 51,
    "Germany": 25,
    "Gibraltar": 101,
    "Greece": 97,
    "Guam": 26,
    "Hawaii": 52,
    "Hong Kong": 96,
    "Hungary": 27,
    "Idaho": 15,
    "Illinois": 53,
    "India": 130,
    "Indiana": 54,
    "Iowa": 55,
    "Ireland": 28,
    "Israel": 102,
    "Italy": 29,
    "Jamaica": 116,
    "Japan": 30,
    "Jersey": 135,
    "Kansas": 56,
    "Kazakhstan": 145,
    "Kentucky": 57,
    "Latvia": 121,
    "Liechtenstein": 136,
    "Lithuania": 131,
    "Louisiana": 58,
    "Macao": 152,
    "Maine": 59,
    "Malaysia": 144,
    "Malta": 133,
    "Maryland": 60,
    "Massachusetts": 61,
    "Mexico": 32,
    "Michigan": 62,
    "Minnesota": 63,
    "Mississippi": 64,
    "Missouri": 65,
    "Montana": 66,
    "Nebraska": 67,
    "Netherlands": 33,
    "Nevada": 68,
    "New Hampshire": 69,
    "New Jersey": 70,
    "New Mexico": 71,
    "New York": 72,
    "New Zealand": 34,
    "North Carolina": 73,
    "North Dakota": 74,
    "Northern Ireland": 93,
    "Norway": 134,
    "Nova Scotia": 151,
    "Ohio": 75,
    "Oklahoma": 76,
    "Oregon": 77,
    "Panama": 125,
    "Pennsylvania": 78,
    "Poland": 146,
    "Portugal": 120,
    "Principality of Monaco": 147,
    "Puerto Rico": 35,
    "Rhode Island": 79,
    "Romania": 119,
    "Russia": 36,
    "San Marino": 104,
    "Scotland": 94,
    "Singapore": 127,
    "Slovenia": 138,
    "South Africa": 114,
    "South Carolina": 80,
    "South Dakota": 81,
    "South Korea": 124,
    "Spain": 37,
    "St. Lucia": 112,
    "St. Martin": 118,
    "Sweden": 150,
    "Switzerland": 38,
    "Taiwan": 106,
    "Tennessee": 82,
    "Texas": 83,
    "Thailand": 99,
    "Turkey": 140,
    "US Virgin Islands": 40,
    "Ukraine": 148,
    "United Arab Emirates": 128,
    "Utah": 84,
    "Vermont": 85,
    "Virginia": 86,
    "Wales": 95,
    "Washington": 87,
    "Washington DC": 49,
    "West Virginia": 88,
    "Wisconsin": 89,
    "Wyoming": 90,
    "Sweeded": 149,
    "_Collector Books_": 132,
}

COUNTRIES = [
    "Afghanistan",
    "Alabama",
    "Alaska",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua and Barbuda",
    "Argentina",
    "Arizona",
    "Arkansas",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bonaire",
    "Bosnia and Herzegovina",
    "Botswana",
    "Bouvet Island",
    "Brazil",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "California",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos (Keeling) Islands",
    "Colombia",
    "Colorado",
    "Comoros",
    "Congo",
    "Congo, The Democratic Republic of the",
    "Connecticut",
    "Cook Islands",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Curaçao",
    "Cyprus",
    "Czech Republic",
    "Côte d'Ivoire",
    "Delaware",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "England",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Falkland Islands",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "Florida",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern Territories",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Hawaii",
    "Heard Island and McDonald Islands",
    "Vatican City State",
    "Honduras",
    "Hong Kong",
    "Hongkong",
    "Hungary",
    "Iceland",
    "Idaho",
    "Illinois",
    "India",
    "Indiana",
    "Indonesia",
    "Iowa",
    "Iran, Islamic Republic of",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kansas",
    "Kazakhstan",
    "Kentucky",
    "Kenya",
    "Kiribati",
    "North Korea",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Lithunia",
    "Louisiana",
    "Luxembourg",
    "Macao",
    "Madagascar",
    "Maine",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique",
    "Maryland",
    "Massachusetts",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Michigan",
    "Micronesia",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Moldova",
    "Principality of Monaco",
    "Mongolia",
    "Montana",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nebraska",
    "Nepal",
    "Netherlands",
    "Nevada",
    "New Caledonia",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "North Carolina",
    "North Dakota",
    "North Macedonia",
    "Northern Ireland",
    "Northern Mariana Islands",
    "Norway",
    "Ohio",
    "Oklahoma",
    "Oman",
    "Oregon",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Pennsylvania",
    "Peru",
    "Philippines",
    "Pitcairn",
    "Poland",
    "Portugal",
    "Private Rollers",
    "Puerto Rico",
    "Qatar",
    "Rhode Island",
    "Romania",
    "Russia",
    "Russian Federation",
    "Rwanda",
    "Réunion",
    "Saint Barthélemy",
    "Saint Helena",
    "Saint Kitts and Nevis",
    "St. Lucia",
    "St. Martin",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Scotland",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Maarten",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Carolina",
    "South Dakota",
    "South Georgia",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "St Lucia",
    "Sudan",
    "Suriname",
    "Svalbard",
    "Sweden",
    "Switzerland",
    "Syrian Arab Republic",
    "Taiwan",
    "Tajikistan",
    "Tanzaniaf",
    "Tennessee",
    "Texas",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks and Caicos Islands",
    "Tuvalu",
    "UAE",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "Uruguay",
    "Utah",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vermont",
    "Viet Nam",
    "Virgin Islands",
    "Virginia",
    "Wales",
    "Wallis and Futuna",
    "Washington",
    "Washington DC",
    "West Virginia",
    "Western Sahara",
    "Wisconsin",
    "Wyoming",
    "Yemen",
    "Zambia",
    "Zimbabwe",
    "Åland Islands",
]
